### ISSUE TITLE
Hard to read output in light scheme colors

### ISSUE THREAD

**Issue by Zerpet** [kevincobain2000/gobrew#102]
## Description

When the system color scheme is set to light, the output of `gobrew` is hard to read because it outputs in yellow font color. This is on a M1 Mac, but I think it will be a problem for Linux users as well. See the below screenshot:

<img width="868" alt="Screenshot 2023-05-09 at 09 25 16" src="https://user-images.githubusercontent.com/1515757/237039757-650190d1-b453-404b-aa74-beaa3979981e.png">
 
## Possible solutions

We could try to change the color output based on system color scheme. I haven't researched how to do this in Go, but I hope this is a solved problem across different platforms 🙂 

Another solution would be to make the color output configurable.

I'm happy to contribute a PR.

**Comment by kevincobain2000** [comment]
That should be easy fix. Thanks for reporting.

**Comment by juev** [comment]
> Another solution would be to make the color output configurable.

Maybe we can use new flag, for example nocolor?
Or use nocolor as default, and add color flag for output with colors?

I like this idea.

**Comment by kevincobain2000** [comment]
I think we can simply check the term color via [termenv](https://github.com/muesli/termenv) as `output.HasDarkBackground()` and set colors according to that

https://github.com/kevincobain2000/gobrew/blob/d1918ffab828d5b402d8b8c5e3cc333b6b7ff0b8/utils/utils.go#L14-L18

**Comment by kevincobain2000** [comment]
How about this?
https://github.com/kevincobain2000/gobrew/pull/103
