### ISSUE TITLE
gobrew self-update always updates

### ISSUE THREAD

**Issue by ethancane** [kevincobain2000/gobrew#108]
Previously when running `gobrew self-update` the tool would check for updates and if found would update the tool, otherwise it would report no update available and that you are already up to date.

Currently when running the above command the tool always seems to download and report 'Upgrade successful' even though no new version has been posted.

Can you please investigate?

Expected behaviour is to run this command and if an update is available then download and upgrade, otherwise do not download approx 6Mb unnecessarily.

Kind regards

**Comment by kevincobain2000** [comment]
lol, yea you are right.

**Comment by kevincobain2000** [comment]
probably next weekend :)

**Comment by kevincobain2000** [comment]
Fixed

```
╭─pulkit.kathuria@JP-GCJKVGQK0G ~/git/re ‹master›
╰─$ gobrew self-update
Downloading 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (6.0/6.0 MB, 2.8 MB/s)
Upgrade successful
╰─$ gobrew version
[INFO] gobrew version is 1.8.5

╭─pulkit.kathuria@JP-GCJKVGQK0G ~/git/re ‹master›
╰─$ gobrew self-update
[INFO] your version is already newest
```
