### ISSUE TITLE
Extend so that we can install golang gotip 

### ISSUE THREAD

**Issue by gedw99** [kevincobain2000/gobrew#109]
Wondering if it can also handle downloading golang beta versions ?

would be nice for smoke testing

**Comment by kevincobain2000** [comment]
Works with beta and rc

**Comment by gedw99** [comment]
true its does

its not possible to get green builds of 1.21 ?

**Comment by kevincobain2000** [comment]
Are those green builds publicly available somewhere?

**Comment by kevincobain2000** [comment]
I am not sure if I follow correctly

**Comment by gedw99** [comment]
Am not sure if they are available.

i think their build farm url

**Comment by gedw99** [comment]
https://dev.golang.org/release

**Comment by kevincobain2000** [comment]
Thanks and no. There is no support for that.
Currently it downloads from the url below

https://github.com/kevincobain2000/gobrew/blob/8455f6eeb1bb7c80a536d9a9461f0bcfe84ed3b0/gobrew.go#L24

If there is tar available there then it shows up on the list of versions that can be installed.

```
╰─$ gobrew ls-remote|grep 1.20 -A 5 -B 5

1.19	1.19.0  1.19.1  1.19.2  1.19.3  1.19.4
	1.19.5  1.19.6  1.19.7  1.19.8  1.19.9
	1.19beta1  1.19rc1  1.19rc2

1.20	1.20.0  1.20.1  1.20.2  1.20.3  1.20.4
	1.20rc1  1.20rc2  1.20rc3
```

--

I am also not sure how badly would an application engineer using Go would want that feature.
Open to ideas tho

**Comment by gedw99** [comment]
yep no worries.

If i find another way will PR it. sure a way in the past, just need to research it again.

**Comment by gedw99** [comment]
finally remembered it:

https://pkg.go.dev/golang.org/dl/gotip 

i am working on this and needed latest go: https://github.com/stealthrocket/wasi-go/tree/main#with-go

Its possible we could incorporate this, and so then devs wont have to think twice

**Comment by kevincobain2000** [comment]
なるほど
I am ok if this feature is available, but probably won't be implementing it anytime soon. Little busy with work these days.
Open to pull reqs if you can submit?

**Comment by gedw99** [comment]
Yeah I will try to find time to make a PR. 

It will be really helpful for me and hopefully others.

will reopen it so others can see this..

**Comment by kevincobain2000** [comment]
sure, thanks.

**Comment by gedw99** [comment]
looks like this will work thanks to  **gotip**  and **gobrew** holding the downloaded artifacts as same structure, but different root paths.

the go env is identical except for 2 things.

---

gotip structure:

``` 
go install golang.org/dl/gotip@latest
gotip download
...
tree /Users/apple/sdk/gotip/
api/   bin/   doc/   lib/   misc/  pkg/   src/   test/

go env
...
GOTOOLDIR='/Users/apple/sdk/gotip/pkg/tool/darwin_amd64'
GOVERSION='devel go1.21-b0e1707 Tue Jun 13 03:06:54 2023 +0000'
```
---

gobrew structure:
``` 
tree /Users/apple/.gobrew/versions/1.20.4/go/
api/   bin/   doc/   lib/   misc/  pkg/   src/   test/

go env
...
GOTOOLDIR="/Users/apple/.gobrew/current/go/pkg/tool/darwin_amd64"
GOVERSION="go1.20.5"
```

---


So its might be as simple as importing **gotip** into gobrew and then calling gotip download and moving the files into tree /Users/apple/.gobrew/versions/gotip/go/ 

gotip is the version.

**Comment by kevincobain2000** [comment]
hmm thanks.
I think it can be kept isolated from `gobrew`, once go is installed users can just use `go install golang.org/dl/gotip@latest`
I still don't see much merit in merging it with `gobrew`

**Comment by gedw99** [comment]
I disagree. You have to do :

so “gotip go env.”

so it messes up all your scripts.

I worked out a way to make it be integrated easily with only minor changes.

Will pr it and you decide.

**Comment by kevincobain2000** [comment]
okay

**Comment by gedw99** [comment]
I have it merged such that code is separate.. you will see what I mean. It is ok if I add a makefile to root of repo ? Just makes things tighter

**Comment by gedw99** [comment]
Will keep git.io.sh obviously :) for curl install

**Comment by kevincobain2000** [comment]
Well. The installation process should just be one liner. I think with makefile there’d be clone as extra step required.

**Comment by kevincobain2000** [comment]
Can I close this issue? @gedw99
