### ISSUE TITLE
Add latest CVES count to each version as `gobrew ls --cves` && `gobrew ls-remote --cves`

### ISSUE THREAD

**Issue by kevincobain2000** [kevincobain2000/gobrew#111]

**Comment by juev** [comment]
Hi!
What do you mean? What is it CVES?

**Comment by kevincobain2000** [comment]
Sorry 
https://www.cvedetails.com/vulnerability-list/vendor_id-14185/product_id-29205/Golang-GO.html

**Comment by juev** [comment]
When a new version of golang is released, I only use Gobrew to install it and switch to it. What can information about existing vulnerabilities in the version be used for?

**Comment by kevincobain2000** [comment]
Mostly the use case I imagined was to have it on the CI, similar to dependabot. 
As many of projects don’t update their versions on CI and go.mod upon EOL. I wanted those CI to fail when a limit of cve score has crossed. 

It was just an idea at the moment.
