### ISSUE TITLE
Failed to install go 1.21.0

### ISSUE THREAD

**Issue by poplary** [kevincobain2000/gobrew#113]
Go 1.21.0 has been released, with the version number being 1.21.0 instead of 1.21. When using gobrew to install the version, it trims the ".0" at the end of the version number. Consequently, accessing https://go.dev/dl/go1.21.darwin-amd64.tar.gz will result in a 404 error since the file does not exist.

![image](https://github.com/kevincobain2000/gobrew/assets/18026812/9723f94e-3d1b-4331-bb99-5b1ab1984064)

BTW, gobrew is a really coooooool tool, thank you~

**Comment by kevincobain2000** [comment]
Caused by https://github.com/kevincobain2000/gobrew/pull/24

**Comment by kevincobain2000** [comment]
Please wait for a little while for the review to finish and I ll merge and release the fix.

Until then please do `gobrew use latest`
