### ISSUE TITLE
Github rate limits

### ISSUE THREAD

**Issue by juev** [kevincobain2000/gobrew#129]
After the update, we encountered a problem with the limit on the number of requests from github:
[122](https://github.com/kevincobain2000/gobrew/pull/122#issuecomment-1711336064)

```
=== RUN   TestUpgrade
Error: ror]: json: cannot unmarshal object into Go value of type []gobrew.Tag
FAIL	github.com/kevincobain2000/gobrew	49.152s
```

It is necessary to add a check to the response code from github and display either information about limiting requests or an error text in order to understand what the problem was.

We also need to add a github token to the request to raise the limits several times.

**Comment by kevincobain2000** [comment]
Or we can comment out that test. Just that test is troublesome. Rest everything is ratelimit proof.
