### ISSUE TITLE
homebrew package ?

### ISSUE THREAD

**Issue by gedw99** [kevincobain2000/gobrew#136]
might make life easier than curl..

**Comment by kevincobain2000** [comment]
Yea. I wanted to do that. And got lost in documentation whenever I started to do it. 
Sometime soon, I need motivation.

**Comment by gedw99** [comment]
sure I know what you mean ...

I guess wait to see if anyone else wants it by voting on this issue. I can live without it.

Maybe do a chocolate for Windows people too.

**Comment by kevincobain2000** [comment]
Yea, one think about home brew I dislike is it takes longer to finish all updates. Curl is sweet and simple. 
anyways let’s see if someone else lands on this issue In future.

**Comment by juev** [comment]
I think the main problem we will face here is the location of the binary file. Gobrew is located in a separate directory in the home space. While brew places all binary files in one common directory in which links are created.

I haven't figured out how to solve this problem yet. If only to untie from the current location. And remove the possibility of updating from the program itself?

**Comment by kevincobain2000** [comment]
Good point. Thanks.
And I think curl will always be the fastest way to install this binary, homebrew often has long long update times.
