### ISSUE TITLE
add TELEMETRY

### ISSUE THREAD

**Issue by kevincobain2000** [kevincobain2000/gobrew#137]
Is there a service where we can add TELEMETRY, to see how this tool is used and how many people use it.

**Comment by juev** [comment]
I think we can create our own service to collect such information.

But, to be honest, it seems like a bad idea to collect data about users, albeit so simple.

This is the same thing that golang developers are trying to implement. And we met quite a lot of negativity.

**Comment by kevincobain2000** [comment]
Thanks.
Yea, I agree. I'll close this. It was just a thought.

**Comment by kevincobain2000** [comment]
This is good to see # of downloads https://tooomm.github.io/github-release-stats/?username=kevincobain2000&repository=gobrew

**Comment by juev** [comment]
I wonder where these statistics come from.

And it’s a little strange that the same file is displayed twice.

**Comment by kevincobain2000** [comment]
From Github API: https://github.com/Somsubhra/github-release-stats/blob/master/js/main.js#L1
