### ISSUE TITLE
does the GitHub action version work with window ?

### ISSUE THREAD

**Issue by gedw99** [kevincobain2000/gobrew#146]
I noticed the matrix example does not show windows.

and for windows we need to set the GOROOT etc after its installed ?

**Comment by kevincobain2000** [comment]
I remember I tried testing it in the past, but action for os: windows didn't work for me, and I gave up.
Here is the `action.yml` for the action https://github.com/kevincobain2000/action-gobrew

**Comment by gedw99** [comment]
Shane .

i know I got makefile working a Ross all 3 of the usual suspects on my other repos. You call the make target from GitHub ci . Same one runs on your laptop. It’s si gke source of truth etc …

**Comment by gedw99** [comment]
Example 

https://github.com/aljorhythm/sapere-server/blob/main/.github/workflows/build.yml
