### ISSUE TITLE
Gobrew comparison bug

### ISSUE THREAD

**Issue by fafato1** [kevincobain2000/gobrew#149]
I already updated the gobrew and tested the new comparison function

![image](https://github.com/kevincobain2000/gobrew/assets/18727712/1bdbb166-9feb-4438-938c-6911a914e07a)

**Comment by kevincobain2000** [comment]
Thanks for reporting.  
that’s weird that it is picking up minor version for go.mod. Go.mod file only contains major versions. 

Will check today.
