### ISSUE TITLE
gobrew can't download package with only major version

### ISSUE THREAD

**Issue by chetratep** [kevincobain2000/gobrew#156]
➜  .gobrew gobrew version
[INFO] gobrew version is 1.9.7
➜  .gobrew gobrew install 1.21
==> [Info] Downloading version: 1.21
==> [Info] Downloading from: https://go.dev/dl/go1.21.darwin-arm64.tar.gz
==> [Info] Downloading to: /Users/chetra.tep/.gobrew/downloads
==> [Info] Downloading version failed: https://go.dev/dl/go1.21.darwin-arm64.tar.gz returned status code 404
==> [Error]: Please check connectivity to url: https://go.dev/dl/go1.21.darwin-arm64.tar.gz

Incorrect download url `https://go.dev/dl/go1.21.darwin-arm64.tar.gz`
`https://go.dev/dl/` doesn't provide package with major version only. Only full version is available.  eg. 1.21.0 => work , 1.21 => download 404 error

**Comment by kevincobain2000** [comment]
Thanks. Will fix it today.

**Comment by kevincobain2000** [comment]
That's because version `1.21` doesn't exist

From Go version `1.21` onwards, the versions are `1.21.0` and so on..

Having said that, I think we can automatically download `1.21.0`  when `1.21` is provided

Similar issues https://github.com/kevincobain2000/gobrew/pull/24

**Comment by kevincobain2000** [comment]
Pull req: https://github.com/kevincobain2000/gobrew/pull/157
