### ISSUE TITLE
It's not clear what version we are running gobrew with

### ISSUE THREAD

**Issue by juev** [kevincobain2000/gobrew#161]
We have the build running:
https://github.com/kevincobain2000/gobrew/actions/runs/7111943967/job/19360930770

During which you can see that version 1.9.9 is being installed, after which it is used to install the dev-latest version: 1.21.5.

But when the go version is launched, version 1.20.11 is returned to us.

Where did this version come from?  I don't have an understanding yet.

As a result, we get an error during the build.

**Comment by kevincobain2000** [comment]
seems like - windows only issue

**Comment by juev** [comment]
Yes, this is specific to windows only.
And version 1.20.11 is the default version on Windows servers.
https://github.com/juev/gobrew-windows/actions/runs/7124279050/job/19398244415

It looks like the environment variables are not set correctly for windows:
https://github.com/kevincobain2000/action-gobrew/blob/master/action.yml

**Comment by juev** [comment]
Will we add this case to the documentation?  To draw attention to the problem?
Or should we just close the current problem?

**Comment by kevincobain2000** [comment]
It's ok to not add it to the docs. Someone from windows if wants can dig this issue up and fix it.

**Comment by juev** [comment]
Ok, thanks!
