### ISSUE TITLE
`git.io.sh` could also set the PATH

### ISSUE THREAD

**Issue by kevincobain2000** [kevincobain2000/gobrew#164]
There is a README instruction as below, which is required after the installation by the user.
If [git.io.sh](https://github.com/kevincobain2000/gobrew/blob/master/git.io.sh) could auto judge what shell and rc file a user may have and append that string for the user after the installation.
 
```
export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"
```

**Comment by juev** [comment]
As far as I know, a number of programs add configuration to all possible configuration files for many shells.

Trying to determine what shell the user is using and what configuration files are very difficult.  For example, because I can use fish, but the script is launched from sh.

**Comment by kevincobain2000** [comment]
Thanks.
