### ISSUE TITLE
[feature requirement] can add mirror url for download go installation package?

### ISSUE THREAD

**Issue by yudar1024** [kevincobain2000/gobrew#171]
for some reason, can not access go.dev to download go installation package. but has some mirror like `https://studygolang.com/dl` can be access . can gobrew provide some way to use the mirror site?

**Comment by kevincobain2000** [comment]
hmm, not sure if we want to go all the way and provide a mirror.
We could however, add fallback urls.

**Comment by juev** [comment]
We can use a separate parameter at startup that would allow us to set or change the current values ​​for a number of variables.  Why not?

**Comment by kevincobain2000** [comment]
I think we can do that already

https://github.com/kevincobain2000/gobrew/blob/e3aeb885124bae7899228ea35235b3614f28e9db/helpers.go#L324

**Comment by juev** [comment]
Oh, that's right!  You can simply change the environment variable.  :)

**Comment by ankitcharolia** [comment]
@juev @yudar1024 :  Kindly try this out https://github.com/ankitcharolia/goenv (ignore if it does not fit to your requirements)
