### ISSUE TITLE
Bug: Windows 10 Symlink required privilege

### ISSUE THREAD

**Issue by vunhatchuong** [kevincobain2000/gobrew#174]
## Problem
Windows 10 symlink required privilege:
![image](https://github.com/kevincobain2000/gobrew/assets/20581504/6a46c5ea-d9a5-43dc-82f2-6e47f75b1e80)

Looks like it hasn't been resolved: https://github.com/golang/go/issues/22874

## Solution

You can either require privilege or use [cmd](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) through [os.exec.Command](https://pkg.go.dev/os/exec#Command):

```go
if runtime.GOOS == "windows" {
	if err = exec.Command("cmd", "mklink", "/d", link , destination).Run(); err == nil {
		return nil
	}
}
```

**Comment by kevincobain2000** [comment]
Thanks for reporting. 
Pull req too please?

**Comment by vunhatchuong** [comment]
Ok I'll try
