### ISSUE TITLE
Add version to `install.sh` or `gobrew self-update`

### ISSUE THREAD

**Issue by kevincobain2000** [kevincobain2000/gobrew#176]
https://github.com/kevincobain2000/gobrew/blob/f81b971520fe03559153914f6f7d1b2cfdeeb4c2/git.io.sh#L62

Provide optional version:

ASIS

```
curl -sLk https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh | sh
```

TOBE

```
curl -sLk https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh | sh - 1.10.5
```

---

Or for someone who has already gobrew installed, then

ASIS

`gobrew self-update`

TO 

`gobrew self-update <version>`

**Comment by juev** [comment]
Hi

Is this necessary in order to be able to roll back if problems are detected? Did I get the meaning right?
