### ISSUE TITLE
gobrew-windows-arm64.exe

### ISSUE THREAD

**Issue by gedw99** [kevincobain2000/gobrew#187]
Using the README instruction, I open a cmd shell on windows arm64 and put in:

```sh

Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.ps1'))


Unable to find a valid release URL!
Unable to match OS: windows, CPU: arm64
Please open an issue at: https://github.com/kevincobain2000/gobrew/issues
Remember to provide your OS, CPU details and powershell version.

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

This is what I get on windows arm64

**Comment by gedw99** [comment]
if you turn off this https://github.com/kevincobain2000/gobrew/blob/master/.goreleaser.yaml#L20, then I can test it on windows 11 arm64 ...

**Comment by gedw99** [comment]
also add amr64 here: https://github.com/kevincobain2000/gobrew/blob/master/git.io.ps1#L33

**Comment by kevincobain2000** [comment]
Thanks. 
I am totally clueless when it comes to windows. And could never understand why would someone not use wsl. 

I’d have to take your word for it. And if the new changes don’t impact current Unix based systems then it’s ok. Feel free to submit the desired changes for windows only.

**Comment by gedw99** [comment]
I will have to fork and test the whole CI / CD thing to make sure it works without creating any regressions.

**Comment by gedw99** [comment]
> wsl

Some users just can't because of architectural constraints on their desktops in certain Orgs where they lock down their desktops.

I use go brew to get golang onto end users desktops

**Comment by kevincobain2000** [comment]
That’s sad. 
anyways you can fork and push your changes. This repo runs the ci on forks too. Feel free to commit many times.

**Comment by gedw99** [comment]
Ok that makes it easier . I did not want to presume. Will give it a try. Will take a few tries I expect

**Comment by gedw99** [comment]
> also add arm64 here: https://github.com/kevincobain2000/gobrew/blob/master/git.io.ps1#L33

hey @kevincobain2000 

```sh 

$archMap = @{
    "amd64" = "x86_64", "i386_64"
    "386"   = "i386", "i686", "x86"    
  }
```

I have no idea what are the names for the extra mapping we ned for Windows arm 64.   I am hoping you might know ?

**Comment by gedw99** [comment]
https://go.dev/doc/install shows that there are no golang builds for windows arm64.

so even if I get this issue working there are no golang builds that it can map to and download.

**Comment by gedw99** [comment]
> https://go.dev/doc/install shows that there are no golang builds for windows arm64.
> 
> so even if I get this issue working there are no golang builds that it can map to and download.

I was wrong. There are golang builds for windows arm64. I tried it and it works fine.

That GOOS and GOARCH is just not what they call a First Class one.

**Comment by gedw99** [comment]
@kevincobain2000 

could we reopen this please ? Go installers do exist as I pointed out above.

**Comment by gedw99** [comment]
also https://github.com/kevincobain2000/gobrew/blob/master/.github/workflows/release.yml can't be triggered by me, to see if the build worked for Windows ARM64 ?

**Comment by kevincobain2000** [comment]
Those will only work when @juev or me push new tag

**Comment by gedw99** [comment]
yeah but not the workflow we need to cause the code I change to get built.

https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow allows manual triggering, but you need to add this to the workflows.

**Comment by kevincobain2000** [comment]
I know

**Comment by kevincobain2000** [comment]
Stale
