### ISSUE TITLE
1.15.15 is missing ?

### ISSUE THREAD

**Issue by gedw99** [kevincobain2000/gobrew#189]
I was playing around with a golang project today. This one...

```sh
module github.com/ajstarks/dchart

go 1.15

```

When I did the normal go brew thing it failed as:

```sh
gobrew use mod
==> [Info] Downloading version: 1.15.15
==> [Info] Downloading from: https://go.dev/dl/go1.15.15.darwin-arm64.tar.gz
==> [Info] Downloading to: /Users/apple/.gobrew/downloads
==> [Info] Extracting from: /Users/apple/.gobrew/downloads/go1.15.15.darwin-arm64.tar.gz
==> [Info] Extracting to: /Users/apple/.gobrew/versions/1.15.15
==> [Info] Extract failed: open /Users/apple/.gobrew/downloads/go1.15.15.darwin-arm64.tar.gz: no such file or directory
```

I guess the golang team did not publish a version of golang that matches ? Or maybe something else ?

**Comment by gedw99** [comment]
when I put https://go.dev/dl/go1.15.15.darwin-arm64.tar.gz into a browser it failed to find it.

so maybe go brew code is wrong in the way it works out where to download things ?

**Comment by kevincobain2000** [comment]
This special cases happen due to change in arm and Darwin releases upon M1 Macs. 

We should have better error messaging for such cases that the version for that architecture doesn’t exist, instead of assuming and trying the downloads.

**Comment by gedw99** [comment]
I see .. so no fix possible ? 

For now, I will force old repos to upgrade to a  more recent golang then as a work around.

**Comment by kevincobain2000** [comment]
>  so no fix possible?

Right, no fix at this moment because the binary on the source also doesn't exist.

**Confirmation:**

> that architecture doesn’t exist, instead of assuming and trying the downloads.

![Screenshot 2024-03-29 at 11 27 09](https://github.com/kevincobain2000/gobrew/assets/629055/0fa5a1c4-5987-4d3a-8731-db25e72366f9)

**Comment by gedw99** [comment]
ok thanks @kevincobain2000 

Such is the situation. 

In my system I will alter my pipeline to:

- add a "go mod edit" to  force golang repos to use a higher version
-  use "gobrew use"  then will work fine.

shall close this, but reopen if needed....

**Comment by ajstarks** [comment]
I've updated to go1.19
