### ISSUE TITLE
go-cover-treemap

### ISSUE THREAD

**Issue by juev** [kevincobain2000/gobrew#193]
A very interesting project:
- [go-cover-treemap][1]

It allows you to arrange the coating in the form of tiles, we can also embed it in pages.

This request is in order not to forget to try to use it. In my opinion, it is very clear.

[1]: https://github.com/nikolaydubina/go-cover-treemap

**Comment by kevincobain2000** [comment]
Interesting!
I can integrate it with https://coveritup.app/readme?org=kevincobain2000&repo=gobrew&branch=master

**Comment by kevincobain2000** [comment]
Actually I had been working on a plugin for Chrome, which is similar to codecov's plugin to highlight the covered lines on Github itself.
That SVG is also kinda neat idea.

**Comment by juev** [comment]
I think integration with coveritup is a great idea!

**Comment by kevincobain2000** [comment]
Thanks
I ll do something this weekend about it then.
Normal upload is straight forward however for value added: I'll look into how to create an SVG for the diff of coverage.

**Comment by kevincobain2000** [comment]
It will be a long development (fun) and my plan is as below:

- [ ] https://github.com/kevincobain2000/cover-totalizer/issues/2
- [ ] https://github.com/kevincobain2000/action-coveritup/issues/21
- [ ] Fix #193 by updating `gobrew/.github/workflows/coveritup.yml`

**Comment by kevincobain2000** [comment]
Too time consuming with very little return on my OSS.
