### ISSUE TITLE
Show go stable version of every major release

### ISSUE THREAD

**Issue by zakisk** [kevincobain2000/gobrew#194]
on command `gobrew ls-remote stable` it should show stable version only.

**Comment by kevincobain2000** [comment]
By stable, you mean no `beta` no `rc`?

**Comment by zakisk** [comment]
No, if user specifies `--stable` flag it should list only stable versions.

**Comment by kevincobain2000** [comment]
I have hard time understanding what versions are considered stable

**Comment by zakisk** [comment]
@kevincobain2000 see how this [version manager](https://github.com/voidint/g?tab=readme-ov-file#usage) does the same job.

**Comment by kevincobain2000** [comment]
Thanks @zakisk will check and get back 

What do you think @juev

**Comment by juev** [comment]
I don't understand what stable version means.

Besides, gobrew is just an installation tool. And I use it to install a specific version that I know. Or to install the latest available version.

I don't understand what the stable version is and what it can be used for.

**Comment by kevincobain2000** [comment]
I also have same opinion @juev 

Thanks for the issue. But I don’t think we need such. It’s a simple tool that does one thing and one thing best. Plus I don’t think users want to remember many cli args.
