### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by juev** [kevincobain2000/gobrew#203]
Our changelog does not correspond to this feeling.

https://github.com/kevincobain2000/gobrew?tab=readme-ov-file#change-log

<img width="838" alt="Screenshot 2024-08-21 at 12 45 48" src="https://github.com/user-attachments/assets/ebbdb8b2-8296-4e32-a2c1-f724fad588ed">

https://github.com/kevincobain2000/gobrew/releases

Here you either don’t write anything at all, or try to collect it automatically.

What do you think @kevincobain2000?

**Comment by kevincobain2000** [comment]
Oops sorry messed up the version there.

**Comment by kevincobain2000** [comment]
For now clean up the CHANGE LOG: https://github.com/kevincobain2000/gobrew/commit/edeeff9fe1a9e012300c4c5e8a66102520b1296d

**Comment by kevincobain2000** [comment]
For some reason, I believe a manually written CHANGE LOG is better for humans to read.

**Comment by kevincobain2000** [comment]
Also mostly the CHANGE LOG is for you and I to keep a track.

**Comment by juev** [comment]
Ok, thanks!
I think the issue can be closed now
