### ISSUE TITLE
 Downloading version failed: file too large 

### ISSUE THREAD

**Issue by maknahar** [kevincobain2000/gobrew#23]
While installing go, getting following error in mocos:

❯ gobrew install 1.16
[Info] Downloading version: 1.16 
[Info]: Downloading version failed: write /Users/mayank/.gobrew/downloads/go1.16.darwin-amd64.tar.gz: file too large 
[Error]: Please check connectivity to url: https://golang.org/dl/go1.16.darwin-amd64.tar.gz

I can download the version via browser without any issue. Any tips on how to bypass this limit?

**Comment by kevincobain2000** [comment]
Hmm this is odd. It seems that connectively was ok and is failing at `io.Copy`, it shouldn't in normal case.

https://github.com/kevincobain2000/gobrew/blob/35a06825063747017aae04fbe1a2572f42915d9a/utils/utils.go#L33-L36

Not to ask but you have enough disk space left on the Mac?

**Comment by maknahar** [comment]
@kevincobain2000 Yes. More than 100GB space is available. I can download the same binary via browser without any issue. Also I tried installing multiple time, just to make sure it is not a network connectivity issue.

**Comment by kevincobain2000** [comment]
I will need your help on this to confirm as I cannot reproduce this.
Probably will prepare another pull req to change the download binary function. Possibly this http://cavaliercoder.com/blog/downloading-large-files-in-go.html

**Comment by maknahar** [comment]
Sure @kevincobain2000 . Would be happy to help. Just let me know.

**Comment by kevincobain2000** [comment]
Please retry, you need to update gobrew once
Solution here: https://github.com/kevincobain2000/gobrew/commit/4abb33dfa2ae1e91287c9bbfdfa07fec5fd41fa2
Solution is from: https://developpaper.com/the-io-copy-usage-of-golang/

```
curl -sLk https://git.io/gobrew | sh -
```

**Comment by kevincobain2000** [comment]
Hi @maknahar Sorry, I didn't tag you in the previous comment. Were you able to verify with the new version?

**Comment by kevincobain2000** [comment]
Hmm not sure.

**Comment by kevincobain2000** [comment]
Let me keep it open to see if any other user has the same issue. So far on my tests on Docker and Macs, I can't reproduce this.
