### ISSUE TITLE
Best path for GOROOT

### ISSUE THREAD

**Issue by wdfinch** [kevincobain2000/gobrew#28]
Hi sorry, there I'm a go noob. I'm installed go using `gobrew` and my IDE is complaining because I don't have `GOROOT` set. What should I set it to with this install method? Maybe some info on this could be added to the docs?

**Comment by kevincobain2000** [comment]
Hi
What is your current GOROOT?

It should have been there already by default. If not then you can set it as

```
export GOROOT=$HOME/.gobrew/current/go
```

**Comment by wdfinch** [comment]
Gotcha. When i run that command I get:

`GOROOT="/home/wfinch/.gobrew/versions/1.18/go"`

That should be fine. I think the issue is I need to export it so my IDE can read it. Thanks so much!
