### ISSUE TITLE
Trying to use older version such as 1.13 dont work

### ISSUE THREAD

**Issue by cas8180** [kevincobain2000/gobrew#29]
Hello,

Recently downloaded your tool with the hopes of back testing my app on older versions of GO. But it doesn't appear to be working on and version below 1.16

![willfawthrop — zsh (figterm) ▸ zsh — 80×24 2022-06-20 08-14-27](https://user-images.githubusercontent.com/1483688/174632672-af3d63c2-149e-4df7-9115-842e78e08506.png)

**Comment by kevincobain2000** [comment]
hmm this is weird because I have no problems

```
╰─$ gobrew install 1.13
[Info] Downloading version: 1.13
[Info] Downloading from: https://golang.org/dl/go1.13.darwin-amd64.tar.gz
[Success]: Response status code: 200
```

You are not behind a proxy and able to get connect to that URL right?
