### ISSUE TITLE
bash syntax is incompatible with sh

### ISSUE THREAD

**Issue by ojwm** [kevincobain2000/gobrew#4]
### Steps to reproduce

  1. Install with `curl -sLk https://git.io/gobrew | sh -`

### Expected

   ```sh
   Installed successfully
   ```

### Actual

   ```sh
   sh: 7: [[: not found
   sh: 9: [[: not found
   sh: 11: [[: not found
   sh: 13: [[: not found
   Installed successfully
   ```

### Possible fix
`[[`, `]]` and `==` are `bash` specific and not compatible with `sh`.\
This can be fixed by specifying `bash` in the shebang `#!/bin/bash` but that would reduce portability.
Some POSIX compatible command alternatives are:
|Bash|POSIX|
|---|---|
|`[[` and `]]`|`[` and `]`|
|`==`|`=`|
|`$OSTYPE`|`uname -o`|

Bash regex:

```bash
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  GOBREW_ARCH_BIN="gobrew-linux-64"
```

POSIX `case` statement with glob patterns:

```sh
case $(uname -o) in
  GNU/Linux*)
    GOBREW_ARCH_BIN='gobrew-linux-64';;
```

Also consider invoking `sh` like this: `sh -c "$(curl -fsSL https://git.io/gobrew)"`

**Comment by kevincobain2000** [comment]
Thanks for the issue together with the solution. I will push the fix today.
