### ISSUE TITLE
[feature request] command completion

### ISSUE THREAD

**Issue by silvioprog** [kevincobain2000/gobrew#51]
Hi.

If possible, it would be useful to allow command completion to `gobrew`. This feature is present in many environment managers. Just as an example, by typing `gobrew in`, it would auto complete to `gobrew install <cursor-here>` by hit in TAB, and another hit in TAB would list the available versions.

**Comment by kevincobain2000** [comment]
Yea, I was also thinking about fish. Let me dig into it.

**Comment by kevincobain2000** [comment]
I am working on it, it'd take a little time.
