### ISSUE TITLE
Can't install go1.14 on macOS

### ISSUE THREAD

**Issue by silvioprog** [kevincobain2000/gobrew#52]
Hi.

I have been trying to install `go1.14` to work on a legacy project, but it seems `gobrew` can't install it in macOS Monterey 12.5.1 (M!).

Please check the `go1.19` in this log below, it is from system, but notice `gobrew` can't switch to `go1.14` and remains allowing to install `go1.14` two or more times:

```
~ % gobrew use 1.14
[Info] Downloading version: 1.14
[Info] Downloading from: https://golang.org/dl/go1.14.darwin-arm64.tar.gz
[Info] Downloading to: ~/.gobrew/downloads
Downloading 100% |████████████████████████████████████████████████████████████| (1.4/1.4 kB, 3.331 MB/s)
[Info] Extracting from: ~/.gobrew/downloads/go1.14.darwin-arm64.tar.gz
[Info] Extracting to: ~/.gobrew/versions/1.14
[Success] Untar to ~/.gobrew/versions/1.14
[Success] Downloaded version: 1.14
[Info] Changing go version to: 1.14
[Success] Changed go version to: 1.14

~ % go version
go version go1.19 darwin/arm64

~ % gobrew use 1.14
[Info] Downloading version: 1.14
[Info] Downloading from: https://golang.org/dl/go1.14.darwin-arm64.tar.gz
[Info] Downloading to: ~/.gobrew/downloads
Downloading 100% |████████████████████████████████████████████████████████████| (1.4/1.4 kB, 3.476 MB/s)
[Info] Extracting from: ~/.gobrew/downloads/go1.14.darwin-arm64.tar.gz
[Info] Extracting to: ~/.gobrew/versions/1.14
[Success] Untar to ~/.gobrew/versions/1.14
[Success] Downloaded version: 1.14
[Info] Changing go version to: 1.14
[Success] Changed go version to: 1.14

~ % go version
go version go1.19 darwin/arm64

~ % tree .gobrew
.gobrew
├── current
│   ├── bin -> ~/.gobrew/versions/1.14/go/bin
│   └── go -> ~/.gobrew/versions/1.14/go
└── versions
    └── 1.14
        └── unknown-pack
```

**Comment by silvioprog** [comment]
Closing. It is not available from Google due to 404 error, so it is not a problem in GoBrew.

**Comment by kevincobain2000** [comment]
Thanks man @silvioprog

**Comment by juev** [comment]
I think we have issue with downloading golang. We cant download, but we do not return error about it.

We can try resolve issue with download function in this ticket, or we can create new?
@kevincobain2000 

<img width="1368" alt="Снимок экрана 2022-08-26 в 10 17 08" src="https://user-images.githubusercontent.com/114635/186845007-9999765e-6790-4027-9d35-96f19075f74a.png">

**Comment by kevincobain2000** [comment]
Same issue is ok. I am currently working on issue #51

**Comment by kevincobain2000** [comment]
yea the download URL for 1.14 doesn't return a response for `arm`

https://golang.org/dl/go1.14.darwin-arm64.tar.gz
In fact, for the arm architecture, only versions `>= 1.16` are available

**Comment by kevincobain2000** [comment]
Ok, I don't this can be fixed to make it to success, because the version `1.14` is not available for `arm`. 
And as @juev mentioned, we should throw an error in such cases.
Following is the pull req https://github.com/kevincobain2000/gobrew/pull/53/files

Will throw error as


```
╰─$ go run cmd/gobrew/main.go install 1.14.1
[Info] Downloading version: 1.14.1
[Info] Downloading from: https://golang.org/dl/go1.14.1.darwin-arm64.tar.gz
[Info] Downloading to: /Users/pulkit.kathuria/.gobrew/downloads
Downloading 100% |████████████████████████████████████████████████████████████████████████████████| (1.4/1.4 kB, 5.849 MB/s)
[Info]: Downloading version failed: downloaded file is too small or doesn't exist
[Error]: Please check connectivity to url: https://golang.org/dl/go1.14.1.darwin-arm64.tar.gz
```
