### ISSUE TITLE
[bug] install via shell/go throws errors

### ISSUE THREAD

**Issue by jordevorstenbosch** [kevincobain2000/gobrew#54]
```sh
~ ❯ curl -sLk https://git.io/gobrew | sh -                                                                                                                                                                   ✔ 2|0 at 10:49:22
Using gobrew version latest

Installed successfully to: /Users/jorde/.gobrew/bin/gobrew
============================
: command not foundw/bin/gobrew: line 1:
/Users/jorde/.gobrew/bin/gobrew: line 2: html: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 3: head: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 4: meta: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 5: title: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 5: middot: command not found
/Users/jorde/.gobrew/bin/gobrew: line 5: /title: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 6: meta: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 7: style: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 8: body: command not found
/Users/jorde/.gobrew/bin/gobrew: line 9: background-color:: command not found
/Users/jorde/.gobrew/bin/gobrew: line 10: syntax error near unexpected token `('
'Users/jorde/.gobrew/bin/gobrew: line 10: `        color: rgba(0, 0, 0, 0.5);
============================

***Please add PATH below to your ~/.bashrc manually***

export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"
```

Installation via Go works fine, but installs to the GOBIN path (default being $HOME/go/bin)

Which results in gobrew being unable to run most commands as it expects the $HOME/.gobrew folder to be the correct directory.

First time diving into Go, so maybe I'm missing something that's obvious to seasoned Go devs.

**Comment by juev** [comment]
@jordevorstenbosch please provide information about your operation system and ARCH?

**Comment by kevincobain2000** [comment]
Thanks @juev for the spot on ask there.

It seems like @jordevorstenbosch has an incorrect binary of gobrew, probably an OS or arch that we don't support _yet_

> operation system and ARCH?

```
echo $(uname -s)
echo $(uname -m)
```

Would you please give the output of this?

**Comment by jordevorstenbosch** [comment]
I'm running MacOS.

So
Darwin
x86_64

**Comment by kevincobain2000** [comment]
That is weird, I have the same and all is good on my machine


As a temporary solution, since your installation with `go` went successful you can do the following:

```
mkdir -p ~/.gobrew/bin ; cp -p $HOME/go/bin/gobrew ~/.gobrew/bin/
```
and then add to your `~/.bashrc` or `~/.zshrc` file

```
export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"
```

> Which results in gobrew being unable to run most commands as it expects the $HOME/.gobrew folder to be the correct directory.

That should solve it, basically, we are creating dir and copying the executable binary in it.

**Comment by kevincobain2000** [comment]
Weird, I have the same

**Comment by jordevorstenbosch** [comment]
I have Go installed via homebrew, not sure if that matters for the Go install. Granted that doesn't explain the issue with the shell install.

Are you running yours in zsh or something else?

**Comment by jordevorstenbosch** [comment]
```shell
/Users/jorde/.gobrew/bin/gobrew: line 1: 
: command not found
/Users/jorde/.gobrew/bin/gobrew: line 2: html: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 3: head: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 4: meta: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 5: middot: command not found
/Users/jorde/.gobrew/bin/gobrew: line 5: title: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 5: /title: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 6: meta: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 7: style: No such file or directory
/Users/jorde/.gobrew/bin/gobrew: line 8: body: command not found
/Users/jorde/.gobrew/bin/gobrew: line 9: background-color:: command not found
/Users/jorde/.gobrew/bin/gobrew: line 10: syntax error near unexpected token `('
/Users/jorde/.gobrew/bin/gobrew: line 10: `        color: rgba(0, 0, 0, 0.5);
'
```

Difference on my system between sh and bash:
```sh
sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
``

```bash
bash --version
GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin21.1.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

If you need me to check something specific just let me know.

**Comment by kevincobain2000** [comment]
Thanks for the details.

2 things here:

**First:**
If `bash -` is working well for you then I should replace it in the README since that is more robust.

**Second:**

The other way of course to install and debug will be like the following:

```
curl -L https://git.io/gobrew > gobrew.sh; chmod +x gobrew.sh
./gobrew.sh
```

Doing this way we can find out if it is the `curl` & `sh -` issue, or and issue with `gobrew.sh`

**Comment by jordevorstenbosch** [comment]
Just using `curl -L https://git.io/gobrew | sh` already works fine.

`curl -L https://git.io/gobrew > gobrew.sh; chmod +x gobrew.sh
./gobrew.sh` works fine as well.

**Comment by kevincobain2000** [comment]
I have removed the troubling `-` of `sh -`
https://github.com/kevincobain2000/gobrew/pull/55

I am sorry I couldn't tell the root cause of why it has happened.
