### ISSUE TITLE
GOROOT will not be changed if official go installed first

### ISSUE THREAD

**Issue by futurist** [kevincobain2000/gobrew#56]
If [official go](https://go.dev/doc/install) version installed first, and want use gobrew to change to another version, then the `GOROOT` path won't changed.

Step to reproduce:
1. [official go](https://go.dev/doc/install) installed(ex:1.17) to /usr/local/go
2. install gobrew, then `gobrew use 1.18`
3. `go env | grep GOROOT` can see the GOROOT won't changed.

Suggestion:
When encountered this case, maybe gobrew can give user a notice to set GOROOT manually?

**Comment by kevincobain2000** [comment]
You actually don’t need to change the GOROOT and keep using the one that is already set by the default go. 
if you do wish to however change it, you could export that env inside your bashrc file.

**Comment by futurist** [comment]
Go binary can work, but the `go build .` cannot work due to below errors like these problems:
https://stackoverflow.com/questions/46693653/compile-version-go1-9-does-not-match-go-tool-version-go1-9-1
https://groups.google.com/g/golang-nuts/c/LUTZK8a8uv4

I think the `GOROOT` location is very important here.

**Comment by kevincobain2000** [comment]
Issuing a warning and/or adding it to README.md is fine enough.
I'd be open to such pull req.
