### ISSUE TITLE
Unable to install on raspberry

### ISSUE THREAD

**Issue by martinskou** [kevincobain2000/gobrew#57]
I'm unable to install gobrew on raspberry pi:

curl -sLk https://git.io/gobrew | sh -
Installing gobrew...

Installed successfully to: /root/.gobrew/bin/gobrew
============================
sh: 49: /root/.gobrew/bin/gobrew: Exec format error
============================

***Please add PATH below to your ~/.bashrc manually***

export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"

uname -m
armv7l

It would be cool if this architecture was supported.
Alterntive a better matching in the bash script and an appropriate error message.

**Comment by juev** [comment]
I think we can to add it

[goreleaser.com//build](https://goreleaser.com/customization/build/)

**Comment by juev** [comment]
@martinskou can you check new version?
