### ISSUE TITLE
A way to adjust the default .gobrew directory with an env variable

### ISSUE THREAD

**Issue by MurtadhaInit** [kevincobain2000/gobrew#77]
It would be great if we could change --using an environment variable-- the default `.gobrew` directory.

It is placed in `$HOME` by default, but that's not XDG compliant (I want it to be `~/.local/share/gobrew/` just like what I do with `pyenv`, `volta` and `vagrant`).

With `pyenv` this is done using `PYENV_ROOT` environment variable.

**Comment by kevincobain2000** [comment]
Doable: #79

**Comment by juev** [comment]
@kevincobain2000 you asked me to review, but merged without it. ;)

where the documentation for this variable? You know about it, but new users cannot find it.
