### ISSUE TITLE
Output library

### ISSUE THREAD

**Issue by juev** [kevincobain2000/gobrew#87]
ref: #85 

we use fatih/color library for output, but in my terminal I dont see colors. :)
and my opinion, we should simplify our output.

<img width="545" alt="Снимок экрана 2023-01-13 в 10 12 27" src="https://user-images.githubusercontent.com/114635/212259511-4b6b387c-8edd-4e77-b6eb-3862a968aee8.png">

For example, switch to zap for our output?

This issue just my opinion and thoughts out loud.

We can discuss and decide what to do in the future, leave everything as it is, or try something else.

**Comment by kevincobain2000** [comment]
Good to close?

**Comment by juev** [comment]
> Good to close?

I think yes, thank you!
