### ISSUE TITLE
Don't error out `gobrew list` after first install

### ISSUE THREAD

**Issue by leodotcloud** [kevincobain2000/gobrew#88]
Steps to repro:

1. `curl -sLk https://git.io/gobrew | sh -`
1. `export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"`
1. `gobrew list`

Error message:
```
gobrew list
==> [Error]: List versions failed: open /Users/username/.gobrew/versions: no such file or directory%
```

This is not at all intuitive on first run. Instead, the error message should point out that no versions have been installed so far.

**Comment by kevincobain2000** [comment]
Yea right. 
Ps: I ll check all the pulls today and merge.

**Comment by juev** [comment]
@kevincobain2000 what do you think?
Should we create empty file on first start and provide message about no one version was installed?
