### ISSUE TITLE
ls-remote lists versions lexicographically and duplicates the list

### ISSUE THREAD

**Issue by Akaame** [kevincobain2000/gobrew#9]
Hey pretty cool project. Wanted to contribute by nitpicking a little bit 😄 

<img width="936" alt="image" src="https://user-images.githubusercontent.com/11539091/122129954-2c7f5e80-ce37-11eb-81f3-a79f2160fe7b.png">

As you can see here ls-remote result is duplicated and the version numbers are listed lexicographically. Ordering of the patch releases is not important but minor releases should be ordered according the numerical/semantic/release order.

**Comment by kevincobain2000** [comment]
Hi @Akaame 
Thanks for raising this issue. I was aware of lexicographical order. I made an attempt but then left it as it is at the time of first release. I ll take your suggestion and fix up on the order. 

Little history on my first attempt

As numeric was not possible - `1.16` was released after `1.6` while numerically `1.6 > 1.16`

Release order is the way I wanted to do it but as ``--sort`` is not available on git versions < 2.0. And to be able to support older versions of git, it wasn't possible.

https://github.com/kevincobain2000/gobrew/blob/35d26fecd277d8fa2b1f401f6f453bf49697ea9b/gobrew.go#L104-L112

I ll look into semantic ordering.

**Comment by kevincobain2000** [comment]
Thanks, I have added semantic version sort for both ``gobrew ls`` and ``gobrew ls-remote`` in #10 and #11 

Screenshots updated for ``ls-remote``

![colors-ls-remote](https://i.imgur.com/j6WP677.png)

**Comment by kevincobain2000** [comment]
This issue is fixed. For now, I had to remove ``beta`` and ``rc`` versions from the tool. Will look into ordering such in another pull req.

# Screenshots

![colors-ls-remote](https://i.imgur.com/gTBCfZL.png)
![colors-ls](https://i.imgur.com/KQbiuyH.png)
