### ISSUE TITLE
how its knows where my goroot is ?

### ISSUE THREAD

**Issue by gedw99** [kevincobain2000/gobrew#98]
works first time - great work

how did it know where my GOPATH is ?

maybe it found it from the previous go install ?

**Comment by gedw99** [comment]
i needed to set this to make it work btw:
```

export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"
export GOROOT="$HOME/.gobrew/current/go"

# use go default..
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
```

**Comment by gedw99** [comment]
I had to also tell vscode where it is. 

<img width="880" alt="Screenshot 2023-04-26 at 13 27 25" src="https://user-images.githubusercontent.com/53147028/234561440-0676de38-97d3-48bc-99a2-3395e3aaa15c.png">

**Comment by kevincobain2000** [comment]
Cool
